name: b2c_platform
description: "Modern B2C platform showcasing Clean Architecture, feature-based structure, BLoC state management, and Flutter best practices. A reference implementation for scalable mobile applications."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+12

environment:
  sdk: '>=3.3.0 <4.0.0'

#Commands
 # flutter pub run build_runner build
 # flutter pub run build_runner watch
 # flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #UI
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.2.19
  flutter_screenutil: ^5.9.0
  figma_squircle: ^0.5.3
  mask_text_input_formatter: ^2.3.0
  pin_code_fields: ^8.0.1
  infinite_scroll_pagination: ^4.0.0
  easy_image_viewer: ^1.5.0
  transparent_image: ^2.0.0
  flutter_svg: ^2.0.5
  cached_network_image: ^3.3.1
  expandable: ^5.0.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  animated_custom_dropdown: ^3.0.0
  dotted_border: ^2.1.0
  package_info_plus: ^4.0.1
  in_app_review: ^2.0.9


  #chache
  get_storage: ^2.0.3
  shared_preferences: ^2.0.18

  #file
  file_picker: ^8.0.3
  mime: ^1.0.4
  image_picker: ^1.1.2


  #others
  dartz: ^0.10.1
  equatable: ^2.0.3
  intl: ^0.20.2
  url_launcher: ^6.1.10
  permission_handler: ^11.3.0
  auto_route: ^8.1.3

  # State management
  flutter_bloc: ^8.1.2

  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #firebase
  firebase_core: ^2.27.0
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^17.0.0

  # API
  internet_connection_checker: ^0.0.1+4
  get_it: ^7.2.0
  dio: ^5.0.2
  http: ^1.2.1
  connectivity_plus: ^2.3.0
  crypto: ^3.0.3
  uuid: ^4.4.0
  convert: ^3.0.1
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

  # Code generation
  freezed: ^2.4.5
  json_serializable: ^6.7.1

  # Testing
  mocktail: ^1.0.1
  bloc_test: ^9.1.5

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  ios_content_mode: center
  android_content_mode: center
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_fore.png"
  adaptive_icon_background: "assets/images/logo_back.png"


flutter_native_splash:

  color: "#FAFAFA"
  image: assets/images/splash.png
  branding: assets/images/branding.png
  android_12:
    color: "#FF4026"

# The following section is specific to Flutter packages.


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf


flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: ru # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/src/common/utils/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false
