// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3tOmt9cVUS3A72bn50vmRbdDSnjGFcTU',
    appId: '1:63306253310:web:c054e46d3bc338c722b6af',
    messagingSenderId: '63306253310',
    projectId: 'b2c_platform-app',
    authDomain: 'b2c_platform-app.firebaseapp.com',
    storageBucket: 'b2c_platform-app.appspot.com',
    measurementId: 'G-06G8TJDNFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Bwek_BdsfAcbclNRzG45a-1MMx6gDvo',
    appId: '1:63306253310:android:e393d11b12c970fe22b6af',
    messagingSenderId: '63306253310',
    projectId: 'b2c_platform-app',
    storageBucket: 'b2c_platform-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5hq75ojMyKsT23SetGSPP_kLyEufOHNQ',
    appId: '1:63306253310:ios:3de89ea075e24a8b22b6af',
    messagingSenderId: '63306253310',
    projectId: 'b2c_platform-app',
    storageBucket: 'b2c_platform-app.appspot.com',
    iosBundleId: 'com.mycompany.vprokatkz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnlKozNoGtN2i2BwmTNzqKlQnx2yrkD6o',
    appId: '1:572901758409:ios:67ed96c6f383fe69f0c418',
    messagingSenderId: '572901758409',
    projectId: 'b2c_platform-c7086',
    storageBucket: 'b2c_platform-c7086.appspot.com',
    iosBundleId: 'com.example.b2c_platform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQuhHw1-5HkadXTTM8dNPxZiBVQhHUeS8',
    appId: '1:572901758409:web:7837f7a84c372681f0c418',
    messagingSenderId: '572901758409',
    projectId: 'b2c_platform-c7086',
    authDomain: 'b2c_platform-c7086.firebaseapp.com',
    storageBucket: 'b2c_platform-c7086.appspot.com',
    measurementId: 'G-0RELJ9GQN5',
  );
}